import { CoverImage } from '../components/CoverImage'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Search } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { searchMusic } from '../services/api'
import { Section } from '../components/Section'
import { SongRow } from '../components/SongRow'

function useDebounced(value: string) { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = setTimeout(() => setDebounced(value), 350); return () => clearTimeout(timer) }, [value]); return debounced }

export function SearchPage() { const [searchParams] = useSearchParams(); const qParam = searchParams.get('q') ?? ''; const [input, setInput] = useState(qParam); useEffect(() => { if (qParam && qParam !== input) setInput(qParam) }, [qParam]); const query = useDebounced(input.trim()); const { data, isFetching, isError, refetch } = useQuery({ queryKey: ['search', query], queryFn: () => searchMusic(query), enabled: query.length > 1, retry: false }); return <div className="page search-page"><div className="search-intro"><h1>Buscar</h1><p>Encuentra una canción, artista, álbum o playlist.</p></div><label className="search-field"><Search size={20}/><input autoFocus value={input} onChange={(event) => setInput(event.target.value)} placeholder="Artistas, álbumes, canciones…"/><kbd>⌘ K</kbd></label>{isFetching && <div className="results skeleton-list">{[1,2,3,4].map((item) => <div className="skeleton-row" key={item}/>)}</div>}{isError && <div className="state"><p>No se pudo conectar con el catálogo.</p><button className="secondary" onClick={() => refetch()}>Reintentar</button></div>}{data && <SearchResults data={data}/>} {!query && <section className="browse"><span className="eyebrow">EXPLORAR</span><h2>Empieza por algo conocido</h2><div className="tag-row">{['Indie alternativo', 'Electronic', 'R&B', 'Focus', 'Rock en español'].map((tag) => <button key={tag} onClick={() => setInput(tag)}>{tag}</button>)}</div></section>}{query && !isFetching && data && !data.songs.length && !data.artists.length && <div className="state"><Search size={28}/><h3>Sin resultados para “{query}”</h3><p>Prueba con otro título o artista.</p></div>}</div> }
export function SearchResults({ data }: { data: Awaited<ReturnType<typeof searchMusic>> }) { return <div className="results"><Section title="Canciones">{data.songs.slice(0,8).map((track, index) => <SongRow track={track} index={index + 1} queue={data.songs} key={track.id}/>)}</Section>{data.artists.length > 0 && <Section title="Artistas"><div className="artist-grid">{data.artists.slice(0,5).map((artist) => <div className="artist-card" key={artist.id}><CoverImage src={artist.thumbnail} alt=""/><b>{artist.name}</b><small>Artista</small></div>)}</div></Section>}</div> }
