import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { RepeatMode, Track } from '../types/music'

type PlayerState = { currentTrack: Track | null; queue: Track[]; history: Track[]; currentIndex: number; isPlaying: boolean; currentTime: number; duration: number; volume: number; repeatMode: RepeatMode; shuffle: boolean; loading: boolean; error: string | null; playTrack: (track: Track, queue?: Track[]) => void; setPlaying: (value: boolean) => void; next: () => void; previous: () => void; seek: (time: number) => void; setDuration: (duration: number) => void; setVolume: (volume: number) => void; setLoading: (loading: boolean) => void; setError: (error: string | null) => void; toggleShuffle: () => void; cycleRepeat: () => void; addToQueue: (track: Track) => void; removeFromQueue: (index: number) => void; clearQueue: () => void }
export const usePlayerStore = create<PlayerState>()(persist((set, get) => ({
  currentTrack: null, queue: [], history: [], currentIndex: -1, isPlaying: false, currentTime: 0, duration: 0, volume: .8, repeatMode: 'off', shuffle: false, loading: false, error: null,
  playTrack: (track, suppliedQueue) => { const queue = suppliedQueue?.length ? suppliedQueue : get().queue; const index = queue.findIndex((item) => item.id === track.id); set((s) => ({ currentTrack: track, queue: suppliedQueue ?? queue, history: [track, ...s.history.filter((item) => item.id !== track.id)].slice(0, 30), currentIndex: index >= 0 ? index : 0, currentTime: 0, isPlaying: true, error: null })) },
  setPlaying: (isPlaying) => set({ isPlaying }),
  next: () => { const s = get(); if (!s.queue.length) return; if (s.repeatMode === 'one') { set({ currentTime: 0, isPlaying: true }); return } const index = s.shuffle ? Math.floor(Math.random() * s.queue.length) : s.currentIndex + 1; if (index >= s.queue.length) { if (s.repeatMode === 'all') set({ currentIndex: 0, currentTrack: s.queue[0], currentTime: 0, isPlaying: true }); else set({ isPlaying: false }); return } set({ currentIndex: index, currentTrack: s.queue[index], currentTime: 0, isPlaying: true }) },
  previous: () => { const s = get(); if (!s.queue.length) return; if (s.currentTime > 4) { set({ currentTime: 0 }); return } const index = s.currentIndex <= 0 ? s.queue.length - 1 : s.currentIndex - 1; set({ currentIndex: index, currentTrack: s.queue[index], currentTime: 0, isPlaying: true }) },
  seek: (currentTime) => set({ currentTime }), setDuration: (duration) => set({ duration }), setVolume: (volume) => set({ volume }), setLoading: (loading) => set({ loading }), setError: (error) => set({ error }), toggleShuffle: () => set((s) => ({ shuffle: !s.shuffle })), cycleRepeat: () => set((s) => ({ repeatMode: s.repeatMode === 'off' ? 'all' : s.repeatMode === 'all' ? 'one' : 'off' })), addToQueue: (track) => set((s) => ({ queue: [...s.queue, track] })), removeFromQueue: (index) => set((s) => ({ queue: s.queue.filter((_, i) => i !== index) })), clearQueue: () => set({ queue: [], currentIndex: -1 })
}), { name: 'sonora-player' }))
